name: Deploy the backend
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.backend
          push: true
          tags: sumeetsinh/todo-app-backend:${{ github.sha }}

      - name: Deploy to SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 3.95.242.5
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo docker pull sumeetsinh/todo-app-backend:${{ github.sha }}
            sudo docker stop user_backend
            sudo docker run --name user_backend -d -p 8080:8080 sumeetsinh/todo-app-backend:${{ github.sha }}
